#!python
from os import environ
from gevent import monkey
monkey.patch_all()

bind = "0.0.0.0:8000"
workers = 1 # THIS IS FOR DEV ONLY.  We want to have more for production.
worker_class = "socketio.sgunicorn.GeventSocketIOWorker"
